services:
  db:
    image: postgres:16
    container_name: ${DB_CONTAINER_NAME}
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_net

  app:
    build: .
    container_name: ${API_CONTAINER_NAME}
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/postgres
    ports:
      - '${API_MAPPED_PORT:-8000}:${API_PORT:-8000}'
    command: ["python", "app/main.py"]
    networks:
      - app_net

volumes:
  db-data:

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.32.0/24
          gateway: 192.168.32.1
