version: '3.8'
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
      POSTGRES_DB: appdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  api:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://appuser:apppass@db:5432/appdb
    ports:
      - "8000:8000"
volumes:
  postgres_data:
