version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: typefriend
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build: .
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/typefriend
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  db_data:
